set(_CATKIN_CURRENT_PACKAGE "ca_gazebo")
set(ca_gazebo_VERSION "0.0.1")
set(ca_gazebo_MAINTAINER "Emiliano Borghi <emiliano.borghi@gmail.com>")
set(ca_gazebo_PACKAGE_FORMAT "1")
set(ca_gazebo_BUILD_DEPENDS "gazebo_ros" "gazebo_plugins" "roscpp" "ca_msgs")
set(ca_gazebo_BUILD_EXPORT_DEPENDS "gazebo_plugins" "gazebo_ros" "roscpp" "ca_msgs" "ca_description" "xacro")
set(ca_gazebo_BUILDTOOL_DEPENDS "catkin")
set(ca_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(ca_gazebo_EXEC_DEPENDS "gazebo_plugins" "gazebo_ros" "roscpp" "ca_msgs" "ca_description" "xacro")
set(ca_gazebo_RUN_DEPENDS "gazebo_plugins" "gazebo_ros" "roscpp" "ca_msgs" "ca_description" "xacro")
set(ca_gazebo_TEST_DEPENDS )
set(ca_gazebo_DOC_DEPENDS )
set(ca_gazebo_URL_WEBSITE "")
set(ca_gazebo_URL_BUGTRACKER "")
set(ca_gazebo_URL_REPOSITORY "")
set(ca_gazebo_DEPRECATED "")